### ISSUE TITLE
Provide an option to have less verbose `model_gen` messages

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/UHDM#128]
The debug messages model_gen outputs are useful while debugging, but are very noisy when running an actual build, which requires a lot of terminal scrolling when opserving the build or continuous integration.

It would be nice to have to have a `set debug_out 0` somewhere as global option in the file to selectively switch debug `puts` on while developing, but have them off by default.

**Comment by alainmarcel** [comment]
Fixed by #129
