### ISSUE TITLE
Model generation does not support multiple inheritance

### ISSUE THREAD

**Issue by rkapuscik** [alainmarcel/UHDM#150]
When using `extends` in model description, only last statement is used.

This is needed for example for `sys func call` (page 1018 in 2017 standard), which should extend both `tf_call` (itself extending `atomic stmt`) and `expr`.

**Comment by alainmarcel** [comment]
Multiple inheritance is not required.
Just inherit from one model (The one with most properties), and inline the
other model's properties.
This happens for a handful of cases.

**Comment by alainmarcel** [comment]
It would create diamond shape inheritance which C++ and Capnp proto would not support

**Comment by alainmarcel** [comment]
There is a workaround, so closing.
