### ISSUE TITLE
Need a deep clone function that deep clones a uhdm subtree including objects and properties

### ISSUE THREAD

**Issue by alainmarcel** [alainmarcel/UHDM#151]
This Serializer function should be auto-generated like the visitor (walker).
Prototype:

namespace UHDM {
class Serializer {
...
any* deepClone(any*);
...

};
};

**Comment by alainmarcel** [comment]
This would be very practical for elaboration

**Comment by alaindargelas** [comment]
Elaboration takes care of this.
