### ISSUE TITLE
Need a function that given a root uhdm node, returns all the sub nodes that match certain criteria

### ISSUE THREAD

**Issue by alainmarcel** [alainmarcel/UHDM#152]
A good use case would be during elaboration, given a construct like cont_assign, always block..., return all the leaf nodes that require binding to an actual signal.
Examples:
 - In the case of cont_assign, its lhs and rhs (if not constant).
 - In the case of an always block all the lhs and rhs from all the (non)blocking stmts and the sensitivity list.
 - return all the data types that need datatype binding

**Comment by alaindargelas** [comment]
Elaboration takes care of this.
