### ISSUE TITLE
Add kokoro users as admins of this repo

### ISSUE THREAD

**Issue by mithro** [alainmarcel/UHDM#176]
- `kokoro-team` user -- Admin permissions
 - `symbiflow-kokoro` user -- Admin permissions
 - `symbiflow-robot` user -- Triage permissions

This enables Kokoro to setup hooks.

**Comment by alaindargelas** [comment]
@kokoro-team
kokoro-team
Awaiting kokoro-team’s response
Pending Invite
 
@symbiflow-kokoro
SymbiFlow Robot (Kokoro Runner)
Awaiting symbiflow-kokoro’s response
Pending Invite
 
@symbiflow-robot
SymbiFlow Robot
Awaiting symbiflow-robot’s response

**Comment by mithro** [comment]
@symbiflow-kokoro and @symbiflow-robot should have accepted.

**Comment by alaindargelas** [comment]
Tim,
I had to convert the account alainmarcel to be an organization to allow
these.
I think I somehow lost the travis aut build in the process, any idea?

**Comment by alaindargelas** [comment]
It works now after I synced the accounts.
