### ISSUE TITLE
Generated code uses singletons

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/UHDM#60]
The generated code uses singletons, e.g. `SymbolFactory::getSymbol()`.

Singletons are an anti-pattern that _always_ will hurt later, so we should change this as soon as possible.
As a simple example when we have multiple independent UHDM models in memory at the same time. We need to change that, that the model operates on some context it has access to (base-class ?)

**Comment by alainmarcel** [comment]
Fixed by #85
