### ISSUE TITLE
Object parameters should not be by value but reference

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/UHDM#70]
For instance, string parameters are currently passed by value

```
bool set_vpiName(std::string data) 
```

This should be
```
bool set_vpiName(const std::string &data) 
```

(or, if we're using c++17, this should actually be `std::string_view` by value. If we aim for C++11, we could use `absl::string_view`, however that would add another dependency, so `const std::string &` is probably best in that case).

**Comment by alainmarcel** [comment]
Fixed by #87
